using System;
using System.Collections.Generic;
using System.Linq;
using Mutagen.Bethesda;
using Mutagen.Bethesda.Synthesis;
using Mutagen.Bethesda.Skyrim;
using System.Threading.Tasks;
using System.IO;
using LoadScreenGen.Settings;

namespace LoadScreenGen {
    public class Program {

        public static string fomodTmpPath = "";

        public static string resourceDirectory = "";
        public static IPatcherState<ISkyrimMod, ISkyrimModGetter>? state = null;

        static Lazy<MainSettings> _Settings = null!;
        public static MainSettings Settings => _Settings.Value;

        public static Task<int> Main(string[] args) {
            return SynthesisPipeline.Instance
                .AddPatch<ISkyrimMod, ISkyrimModGetter>(RunPatch)
                .SetAutogeneratedSettings(
                    nickname: "Settings",
                    path: "settings.json",
                    out _Settings)
                .SetTypicalOpen(GameRelease.SkyrimLE, "YourPatcher.esp")
                .Run(args);
        }

        public static void RunPatch(IPatcherState<ISkyrimMod, ISkyrimModGetter> state) {
            //Your code here!
            Program.resourceDirectory = state.ExtraSettingsDataPath;
            Program.state = state;

            var sse = state.GameRelease != GameRelease.SkyrimLE && state.GameRelease != GameRelease.EnderalLE;
            string templatePath;
            if(sse) {
                templatePath = Path.Combine(resourceDirectory, "TemplateSSE.nif");
            } else {
                templatePath = Path.Combine(resourceDirectory, "TemplateLE.nif");
            }
            SkyrimRelease release = sse ? SkyrimRelease.SkyrimSE : SkyrimRelease.SkyrimLE;




            if(!Settings.authorSettings.enableAuthorMode) {
                if(Directory.Exists(Settings.userSettings.sourcePath)) {
                    var imageArray = TextureGen.ProcessTextures(Settings.userSettings.sourcePath, new string[] { Path.Combine(state.DataFolderPath, "textures", Settings.userSettings.defaultModFolder) }, new int[] { Settings.userSettings.imageResolution }, Settings.userSettings.includeSubDirs);

                    string meshDirectory = Path.Combine(state.DataFolderPath, "meshes", Settings.userSettings.defaultModFolder);
                    string textureDirectory = Path.Combine("textures", Settings.userSettings.defaultModFolder);
                    Directory.CreateDirectory(meshDirectory);
                    MeshGen.CreateMeshes(imageArray.ToList(), meshDirectory, textureDirectory, templatePath, Settings.userSettings.screenWidth * 1.0 / Settings.userSettings.screenHeight, Settings.userSettings.borderOption);
                    PluginGen.CreateEsp(state.PatchMod, imageArray, Settings.userSettings.defaultModFolder, Settings.userSettings.defaultPrefix, true, Settings.userSettings.frequency, Settings.userSettings.loadScreenPriority);
                }
            } else {
                if(Directory.Exists(Settings.authorSettings.sourcePath)) {
                    fomodTmpPath = Path.Combine(Path.GetTempPath(), "JLoadScreens");
                    Directory.CreateDirectory(fomodTmpPath);
                    Directory.Delete(fomodTmpPath, true);
                    Directory.CreateDirectory(fomodTmpPath);

                    var targetDirectory = new List<string>();
                    var imageResolution = new List<int>();

                    targetDirectory.Add(Path.Combine(Path.Combine(state.DataFolderPath, fomodTmpPath, "textures", "2K"), "textures", Settings.authorSettings.modFolder));
                    imageResolution.Add(2048);
                    if(Settings.authorSettings.resolutionSettings.fourK) {
                        targetDirectory.Add(Path.Combine(Path.Combine(state.DataFolderPath, fomodTmpPath, "textures", "4K"), "textures", Settings.authorSettings.modFolder));
                        imageResolution.Add(4096);
                    }
                    if(Settings.authorSettings.resolutionSettings.eightK) {
                        targetDirectory.Add(Path.Combine(Path.Combine(state.DataFolderPath, fomodTmpPath, "textures", "8K"), "textures", Settings.authorSettings.modFolder));
                        imageResolution.Add(8192);
                    }

                    string textureDirectory = Path.Combine("textures", Settings.authorSettings.modFolder);
                    var imageArray = TextureGen.ProcessTextures(Settings.authorSettings.sourcePath, targetDirectory.ToArray(), imageResolution.ToArray(), Settings.authorSettings.includeSubDirs);
                    HashSet<BorderOption> borderOptions = new();
                    if(Settings.authorSettings.borderSettings.includeNormal) {
                        borderOptions.Add(BorderOption.Normal);
                    }
                    if(Settings.authorSettings.borderSettings.includeCrop) {
                        borderOptions.Add(BorderOption.Crop);
                    }
                    if(Settings.authorSettings.borderSettings.includeFixedHeight) {
                        borderOptions.Add(BorderOption.FixedHeight);
                    }
                    if(Settings.authorSettings.borderSettings.includeFixedWidth) {
                        borderOptions.Add(BorderOption.FixedWidth);
                    }
                    if(Settings.authorSettings.borderSettings.includeStretch) {
                        borderOptions.Add(BorderOption.Stretch);
                    }
                    HashSet<LoadingScreenPriority> loadScreenPriorities = new();
                    if(Settings.authorSettings.prioritySettings.includeStandalone) {
                        loadScreenPriorities.Add(LoadingScreenPriority.Standalone);
                    }
                    if(Settings.authorSettings.prioritySettings.includeReplacer) {
                        loadScreenPriorities.Add(LoadingScreenPriority.Replacer);
                    }
                    if(Settings.authorSettings.prioritySettings.includeFrequency) {
                        loadScreenPriorities.Add(LoadingScreenPriority.Frequency);
                    }
                    if(Settings.authorSettings.prioritySettings.includeMcm) {
                        loadScreenPriorities.Add(LoadingScreenPriority.Mcm);
                    }
                    if(Settings.authorSettings.prioritySettings.includeDebug) {
                        loadScreenPriorities.Add(LoadingScreenPriority.Debug);
                    }

                    var aspectRatios = AspectRatio.Parse(Settings.authorSettings.aspectRatios);
                    foreach(var borderOption in borderOptions) {
                        foreach(var aspectRatio in aspectRatios) {
                            var displayRatio = aspectRatio.w * 1.0 / aspectRatio.h;
                            string meshDirectory = Path.Combine(state.DataFolderPath, fomodTmpPath, "meshes");
                            meshDirectory = Path.Combine(meshDirectory, "" + aspectRatio);
                            meshDirectory = Path.Combine(meshDirectory, "" + borderOption);
                            meshDirectory = Path.Combine(meshDirectory, "meshes", Settings.authorSettings.modFolder);
                            Directory.CreateDirectory(meshDirectory);
                            Logger.Log(meshDirectory);
                            MeshGen.CreateMeshes(imageArray.ToList(), meshDirectory, textureDirectory, templatePath, displayRatio, borderOption);
                        }
                    }
                    List<int> frequencyList = new();
                    int defaultFrequency;
                    var frequencyArray = Settings.authorSettings.frequencyList.Split(",");
                    foreach(var s in frequencyArray) {
                        frequencyList.Add(int.Parse(s));
                        if(!loadScreenPriorities.Contains(LoadingScreenPriority.Frequency) && !loadScreenPriorities.Contains(LoadingScreenPriority.Mcm)) {
                            // no frequency choice
                            break;
                        }
                    }
                    defaultFrequency = frequencyList.First();
                    foreach(var loadScreenPriority in loadScreenPriorities) {
                        var newFrequencyList = new List<int>();
                        if((loadScreenPriority == LoadingScreenPriority.Frequency) || (loadScreenPriority == LoadingScreenPriority.Mcm)) {
                            newFrequencyList.AddRange(frequencyList);
                        } else {
                            newFrequencyList.Add(0);
                        }
                        foreach(var frequency in newFrequencyList) {
                            if(Settings.authorSettings.loadingScreenText != LoadingScreenText.Never) {
                                CreatePluginOptions(release, state.DataFolderPath, frequency, true, imageArray, loadScreenPriority);
                            }
                            if(Settings.authorSettings.loadingScreenText != LoadingScreenText.Always) {
                                CreatePluginOptions(release, state.DataFolderPath, frequency, false, imageArray, loadScreenPriority);
                            }
                        }
                    }
                    Logger.Log(fomodTmpPath);
                    FomodGen.CreateFomod(imageArray, aspectRatios, borderOptions, loadScreenPriorities, frequencyList, defaultFrequency, imageResolution, targetDirectory);

                    //Directory.Delete(fomodTmpPath, true);
                }
            }
        }
        public static string GetPluginName(int frequency, bool includeText, LoadingScreenPriority loadScreenPriority) {
            return "FOMOD_M" + (includeText ? "1" : "0") + "_C_" + loadScreenPriority + "_P" + frequency + "_FOMODEND_" + Settings.authorSettings.pluginName;
        }
        public static void CreatePluginOptions(SkyrimRelease release, string dataPath, int frequency, bool includeText, Image[] imageArray, LoadingScreenPriority loadScreenPriority) {
            var pluginPath = GetPluginName(frequency, includeText, loadScreenPriority);
            pluginPath = Path.Combine(fomodTmpPath, pluginPath);
            var mod = PluginGen.CreateNewEsp(pluginPath, release, dataPath);
            PluginGen.CreateEsp(mod, imageArray, Settings.authorSettings.modFolder, Settings.authorSettings.pluginPrefix, includeText, frequency, loadScreenPriority);
            PluginGen.WriteNewEsp(mod, pluginPath);
        }
    }
    public class AspectRatio {
        public int w;
        public int h;
        public AspectRatio(int w, int h) {
            this.w = w;
            this.h = h;
        }

        public override bool Equals(object? obj) {
            if(obj is AspectRatio asAspectRatio) {
                return asAspectRatio.w == w && asAspectRatio.h == h;
            }
            return false;
        }

        public static HashSet<AspectRatio> Parse(string parseString) {
            HashSet<AspectRatio> set = new();
            var singleStrings = parseString.Split(",");
            foreach(string s in singleStrings) {
                var whString = s.Split(":");
                if(whString.Length != 2) {
                    throw new ArgumentException("Could not parse Aspect Ratio string:<" + parseString + ">");
                }
                set.Add(new AspectRatio(int.Parse(whString[0]), int.Parse(whString[1])));
            }
            return set;
        }

        public override string ToString() {
            return w + "x" + h;
        }

        public override int GetHashCode() {
            return Tuple.Create(w, h).GetHashCode();
        }
    }
}
